# Laboratorio 1. Generación de datos sintéticos del dominio de Matrícula

**Objetivo:** Configurar el entorno de trabajo y preparar las librerías necesarias para la generación del conjunto de datos sintético basado en el dominio de matrícula de SIMAT.

In [1]:
from faker import Faker
import pandas as pd
import numpy as np
from pathlib import Path
import sys

proyecto = Path.cwd().parent
sys.path.append(str(proyecto))

faker = Faker("es_CO")

RUTA_DATA = Path("../data/raw")

RUTA_DATA.mkdir(parents=True, exist_ok=True)

print("Entorno inicializado correctamente.")
print(f"Nombre de prueba: {faker.name()}")

Entorno inicializado correctamente.
Nombre de prueba: Katherin Mejía Becerra

In [2]:
from generators.catalogos import generar_etc

etc = generar_etc()

etc.head()

,codigo_etc,nombre_etc,fecha_carga,origen,version_dato
0,ETC001,Entidad Territorial 1,2026-10-25 21:54:43.411674,SIMAT_SINTETICO,1
1,ETC002,Entidad Territorial 2,2026-10-25 21:54:43.411674,SIMAT_SINTETICO,1
2,ETC003,Entidad Territorial 3,2026-10-25 21:54:43.411674,SIMAT_SINTETICO,1
3,ETC004,Entidad Territorial 4,2026-10-25 21:54:43.411674,SIMAT_SINTETICO,1
4,ETC005,Entidad Territorial 5,2026-10-25 21:54:43.411674,SIMAT_SINTETICO,1

In [3]:
print(f"Total ETC generadas: {len(etc)}")

display(etc.sample(5))

Total ETC generadas: 20

,codigo_etc,nombre_etc,fecha_carga,origen,version_dato
14,ETC015,Entidad Territorial 15,2026-10-25 21:54:43.411674,SIMAT_SINTETICO,1
10,ETC011,Entidad Territorial 11,2026-10-25 21:54:43.411674,SIMAT_SINTETICO,1
0,ETC001,Entidad Territorial 1,2026-10-25 21:54:43.411674,SIMAT_SINTETICO,1
13,ETC014,Entidad Territorial 14,2026-10-25 21:54:43.411674,SIMAT_SINTETICO,1
6,ETC007,Entidad Territorial 7,2026-10-25 21:54:43.411674,SIMAT_SINTETICO,1

In [5]:
from generators.catalogos import generar_etc

etc = generar_etc()

etc.head()

,codigo_etc,nombre_etc,fecha_carga,origen,version_dato
0,ETC001,Entidad Territorial 1,2026-10-25 21:55:17.952676,SIMAT_SINTETICO,1
1,ETC002,Entidad Territorial 2,2026-10-25 21:55:17.952676,SIMAT_SINTETICO,1
2,ETC003,Entidad Territorial 3,2026-10-25 21:55:17.952676,SIMAT_SINTETICO,1
3,ETC004,Entidad Territorial 4,2026-10-25 21:55:17.952676,SIMAT_SINTETICO,1
4,ETC005,Entidad Territorial 5,2026-10-25 21:55:17.952676,SIMAT_SINTETICO,1

In [6]:
from generators.catalogos import generar_etc

etc = generar_etc()

etc.head()

,codigo_etc,nombre_etc,fecha_carga,origen,version_dato
0,ETC001,Entidad Territorial 1,2026-10-25 21:57:52.408137,SIMAT_SINTETICO,1
1,ETC002,Entidad Territorial 2,2026-10-25 21:57:52.408137,SIMAT_SINTETICO,1
2,ETC003,Entidad Territorial 3,2026-10-25 21:57:52.408137,SIMAT_SINTETICO,1
3,ETC004,Entidad Territorial 4,2026-10-25 21:57:52.408137,SIMAT_SINTETICO,1
4,ETC005,Entidad Territorial 5,2026-10-25 21:57:52.408137,SIMAT_SINTETICO,1

In [11]:
from generators.catalogos import generar_municipios

municipios = generar_municipios()

display(municipios.head())

,codigo_municipio,nombre_municipio,codigo_etc,fecha_carga,origen,version_dato
0,MUN0001,Municipio 1,ETC001,2026-10-25 22:03:07.351093,SIMAT_SINTETICO,1
1,MUN0002,Municipio 2,ETC002,2026-10-25 22:03:07.351093,SIMAT_SINTETICO,1
2,MUN0003,Municipio 3,ETC003,2026-10-25 22:03:07.351093,SIMAT_SINTETICO,1
3,MUN0004,Municipio 4,ETC004,2026-10-25 22:03:07.351093,SIMAT_SINTETICO,1
4,MUN0005,Municipio 5,ETC005,2026-10-25 22:03:07.351093,SIMAT_SINTETICO,1

In [12]:
from generators.sedes import generar_sedes

sedes = generar_sedes(municipios)

display(sedes.head())

,codigo_sede,nombre_sede,codigo_municipio,codigo_etc,estado,fecha_carga,origen,version_dato
0,SED00001,Institución Educativa 1,MUN0001,ETC001,ACTIVA,2026-10-25 22:03:17.738719,SIMAT_SINTETICO,1
1,SED00002,Institución Educativa 2,MUN0002,ETC002,ACTIVA,2026-10-25 22:03:17.738719,SIMAT_SINTETICO,1
2,SED00003,Institución Educativa 3,MUN0003,ETC003,ACTIVA,2026-10-25 22:03:17.738719,SIMAT_SINTETICO,1
3,SED00004,Institución Educativa 4,MUN0004,ETC004,ACTIVA,2026-10-25 22:03:17.738719,SIMAT_SINTETICO,1
4,SED00005,Institución Educativa 5,MUN0005,ETC005,ACTIVA,2026-10-25 22:03:17.738719,SIMAT_SINTETICO,1

In [13]:
print(f"Sedes generadas: {len(sedes)}")

sedes.sample(5)

Sedes generadas: 500

,codigo_sede,nombre_sede,codigo_municipio,codigo_etc,estado,fecha_carga,origen,version_dato
75,SED00076,Institución Educativa 76,MUN0076,ETC016,ACTIVA,2026-10-25 22:03:17.738719,SIMAT_SINTETICO,1
401,SED00402,Institución Educativa 402,MUN0042,ETC002,ACTIVA,2026-10-25 22:03:17.740223,SIMAT_SINTETICO,1
195,SED00196,Institución Educativa 196,MUN0076,ETC016,ACTIVA,2026-10-25 22:03:17.739725,SIMAT_SINTETICO,1
205,SED00206,Institución Educativa 206,MUN0086,ETC006,ACTIVA,2026-10-25 22:03:17.739725,SIMAT_SINTETICO,1
384,SED00385,Institución Educativa 385,MUN0025,ETC005,ACTIVA,2026-10-25 22:03:17.740223,SIMAT_SINTETICO,1

In [14]:
from generators.estudiantes import generar_estudiantes

estudiantes = generar_estudiantes(sedes)

display(estudiantes.head())

,id_estudiante,tipo_documento,numero_documento,nombres,apellidos,genero,fecha_nacimiento,direccion,telefono,codigo_sede,codigo_municipio,codigo_etc,fecha_carga,origen,version_dato
0,EST00000001,CC,8050853588,Dora,Mendoza,F,2014-09-22,"Cr. 61 # 8-94\n252461\nChía, Cundinamarca",3292990804,SED00001,MUN0001,ETC001,2026-10-25 22:08:06.324995,SIMAT_SINTETICO,1
1,EST00000002,RC,5003390046,Sebastián,Zambrano,M,2008-12-29,Tr. 46 # 1-21 Sur\nEtapa 6 apartamento 10\n252...,+576015565279,SED00002,MUN0002,ETC002,2026-10-25 22:08:06.325494,SIMAT_SINTETICO,1
2,EST00000003,CC,7872248026,Enrique,Campo,F,2010-03-02,Cl. 71Z # 9V-5 Este\nTorre 3 apartamento 45\n4...,573181926118,SED00003,MUN0003,ETC003,2026-10-25 22:08:06.325989,SIMAT_SINTETICO,1
3,EST00000004,RC,7955639071,Elena,Becerra,F,2012-11-14,"Transversal 73 # 49-65 Sur\n179954\nMarulanda,...",+573142831402,SED00004,MUN0004,ETC004,2026-10-25 22:08:06.326485,SIMAT_SINTETICO,1
4,EST00000005,RC,4797889053,Claudia,Aguirre,F,2019-08-16,"Calle 30 # 50I-61\n733767\nSanta Isabel, Tolima",(+57)3004163825,SED00005,MUN0005,ETC005,2026-10-25 22:08:06.326981,SIMAT_SINTETICO,1

In [15]:
print(f"Total estudiantes: {len(estudiantes)}")

estudiantes.sample(5)

Total estudiantes: 50000

,id_estudiante,tipo_documento,numero_documento,nombres,apellidos,genero,fecha_nacimiento,direccion,telefono,codigo_sede,codigo_municipio,codigo_etc,fecha_carga,origen,version_dato
9907,EST00009908,RC,4663417127,María,Castro,F,2012-09-28,"Av. Uramita # 29-4 Sur\n131308\nTurbaná, Bolívar",6045769339,SED00408,MUN0048,ETC008,2026-10-25 22:08:08.312808,SIMAT_SINTETICO,1
30928,EST00030929,CC,9099788726,Alexander,Bohórquez,M,2014-11-21,"Av. calle 43 # 1-61 Este\n410618\nSanta María,...",+576054412571,SED00429,MUN0069,ETC009,2026-10-25 22:08:12.531117,SIMAT_SINTETICO,1
9783,EST00009784,RC,143139736,Andrés,Zapata,F,2017-03-29,Av. Chinú # 4-19\nTorre 6 apartamento 401\n054...,(+57) 318 520 98 61,SED00284,MUN0044,ETC004,2026-10-25 22:08:08.288450,SIMAT_SINTETICO,1
35666,EST00035667,RC,9251888140,Lucía,Flórez,F,2013-02-23,Avenida calle 25 # 8-22 Sur\nApto. 50\n737560\...,607 119 76 94,SED00167,MUN0047,ETC007,2026-10-25 22:08:13.507156,SIMAT_SINTETICO,1
4721,EST00004722,TI,1009568347,Juan,Pérez,M,2013-04-10,Cl. 2C # 3-25 Sur\nOficina 73\n681315\nCoromor...,3064378173,SED00222,MUN0102,ETC002,2026-10-25 22:08:07.257216,SIMAT_SINTETICO,1

In [16]:
from generators.matriculas import generar_matriculas

matriculas = generar_matriculas(estudiantes)

display(matriculas.head())

,id_matricula,id_estudiante,anio,grado,jornada,estado_matricula,fecha_matricula,codigo_sede,codigo_municipio,codigo_etc,fecha_carga,origen,version_dato
0,MAT00000001,EST00000001,2026,1,Tarde,CANCELADA,2026-01-15,SED00001,MUN0001,ETC001,2026-10-25 22:22:14.208834,SIMAT_SINTETICO,1
1,MAT00000002,EST00000002,2026,8,Única,ACTIVA,2026-01-15,SED00002,MUN0002,ETC002,2026-10-25 22:22:14.208834,SIMAT_SINTETICO,1
2,MAT00000003,EST00000003,2026,3,Única,CANCELADA,2026-01-15,SED00003,MUN0003,ETC003,2026-10-25 22:22:14.208834,SIMAT_SINTETICO,1
3,MAT00000004,EST00000004,2026,8,Tarde,CANCELADA,2026-01-15,SED00004,MUN0004,ETC004,2026-10-25 22:22:14.208834,SIMAT_SINTETICO,1
4,MAT00000005,EST00000005,2026,8,Única,ACTIVA,2026-01-15,SED00005,MUN0005,ETC005,2026-10-25 22:22:14.208834,SIMAT_SINTETICO,1

In [17]:
from utils.calidad import insertar_errores

estudiantes_error, matriculas_error = insertar_errores(
    estudiantes,
    matriculas
)

In [18]:
display(estudiantes_error.loc[[0,10,20]])

,id_estudiante,tipo_documento,numero_documento,nombres,apellidos,genero,fecha_nacimiento,direccion,telefono,codigo_sede,codigo_municipio,codigo_etc,fecha_carga,origen,version_dato
0,EST00000001,CC,8.050854e+09,Dora,Mendoza,F,2014-09-22,"Cr. 61 # 8-94\n252461\nChía, Cundinamarca",3292990804,SED00001,MUN0001,ETC001,2026-10-25 22:08:06.324995,SIMAT_SINTETICO,1
10,EST00000011,RC,8.050854e+09,Patricia,Martínez,F,2010-12-12,Av. Valderrama # 5-64\nCasa 85\n251141\nChipaq...,325 904 26 06,SED00011,MUN0011,ETC011,2026-10-25 22:08:06.328477,SIMAT_SINTETICO,1
20,EST00000021,TI,NaN,Liliana,Flórez,F,2014-06-28,"Cr. 6ª # 4-4 Este\n525006\nMagüí, Nariño",(+57) 301 219 66 82,SED00021,MUN0021,ETC001,2026-10-25 22:08:06.331969,SIMAT_SINTETICO,1

In [19]:
display(matriculas_error.loc[[30,40,50,60]])

,id_matricula,id_estudiante,anio,grado,jornada,estado_matricula,fecha_matricula,codigo_sede,codigo_municipio,codigo_etc,fecha_carga,origen,version_dato
30,MAT00000031,EST00000031,2026,10,Tarde,CANCELADA,2026-01-15,SED99999,MUN0031,ETC011,2026-10-25 22:22:14.208834,SIMAT_SINTETICO,1
40,MAT00000041,EST00000041,2026,8,NOCTURNA,ACTIVA,2026-01-15,SED00041,MUN0041,ETC001,2026-10-25 22:22:14.208834,SIMAT_SINTETICO,1
50,MAT00000051,EST00000051,2026,1,Mañana,DESCONOCIDO,2026-01-15,SED00051,MUN0051,ETC011,2026-10-25 22:22:14.208834,SIMAT_SINTETICO,1
60,MAT00000061,EST00000061,2026,11,Única,ACTIVA,2026-01-15,SED00061,MUN0061,ETC999,2026-10-25 22:22:14.209332,SIMAT_SINTETICO,1

In [20]:
from utils.exportador import exportar_csv

In [21]:
exportar_csv(etc, "etc")
exportar_csv(municipios, "municipios")
exportar_csv(sedes, "sedes")
exportar_csv(estudiantes_error, "estudiantes")
exportar_csv(matriculas_error, "matriculas")

Archivo exportado: ..\data\raw\etc.csv
Archivo exportado: ..\data\raw\municipios.csv
Archivo exportado: ..\data\raw\sedes.csv
Archivo exportado: ..\data\raw\estudiantes.csv
Archivo exportado: ..\data\raw\matriculas.csv