# Laboratorio 1. Generación de datos sintéticos del dominio de Matrícula

**Objetivo:** Configurar el entorno de trabajo y preparar las librerías necesarias para la generación del conjunto de datos sintético basado en el dominio de matrícula de SIMAT.

In [1]:
from faker import Faker
import pandas as pd
import numpy as np
from pathlib import Path

faker = Faker("es_CO")

RUTA_DATA = Path("../data/raw")

RUTA_DATA.mkdir(parents=True, exist_ok=True)

print("Entorno inicializado correctamente.")
print(f"Nombre de prueba: {faker.name()}")

Entorno inicializado correctamente.
Nombre de prueba: Anderson Luis Agudelo Trujillo

In [2]:
from generators.catalogos import generar_etc

etc = generar_etc()

etc.head()

,codigo_etc,nombre_etc,fecha_carga,origen,version_dato
0,ETC001,Entidad Territorial 1,2026-10-25 21:29:50.276876,SIMAT_SINTETICO,1
1,ETC002,Entidad Territorial 2,2026-10-25 21:29:50.277589,SIMAT_SINTETICO,1
2,ETC003,Entidad Territorial 3,2026-10-25 21:29:50.277589,SIMAT_SINTETICO,1
3,ETC004,Entidad Territorial 4,2026-10-25 21:29:50.277589,SIMAT_SINTETICO,1
4,ETC005,Entidad Territorial 5,2026-10-25 21:29:50.277589,SIMAT_SINTETICO,1

In [3]:
print(f"Total ETC generadas: {len(etc)}")

display(etc.sample(5))

Total ETC generadas: 20

,codigo_etc,nombre_etc,fecha_carga,origen,version_dato
12,ETC013,Entidad Territorial 13,2026-10-25 21:29:50.277589,SIMAT_SINTETICO,1
1,ETC002,Entidad Territorial 2,2026-10-25 21:29:50.277589,SIMAT_SINTETICO,1
17,ETC018,Entidad Territorial 18,2026-10-25 21:29:50.277589,SIMAT_SINTETICO,1
16,ETC017,Entidad Territorial 17,2026-10-25 21:29:50.277589,SIMAT_SINTETICO,1
7,ETC008,Entidad Territorial 8,2026-10-25 21:29:50.277589,SIMAT_SINTETICO,1

In [6]:
from src.generators.catalogos import generar_etc, generar_municipios

municipios = generar_municipios()

display(municipios.head())

ModuleNotFoundError: No module named 'src'